--- pshy_emptyscriptslot.lua
--
-- This script is just to be inserted at the end, so that you can insert a custom script easily.
--
-- @require_priority 90
--
-- \/ INSERT YOUR SCRIPT JUST BELOW THIS LINE \/
-- /\ INSERT YOUR SCRIPT JUST OVER THIS LINE /\
