--- pshy.essentials_plus
--
-- Useful optional modules.
--
-- @author TFM:Pshy#3752 DC:Pshy#7998
--
--- @require pshy_adminchat.lua
--- @require pshy_alternatives.lua
--- @require pshy_assert.lua
--- @require pshy_ban.lua
--- @require pshy_bindmouse.lua
--- @require pshy_bonuses.lua
--- @require pshy_bonuses_all.lua
--- @require pshy_bonuses_mapext.lua
--- @require pshy_changeimage.lua
--- @require pshy_commands_fun.lua
--- @require pshy_commands_lua.lua
--- @require pshy_commands_modules.lua
--- @require pshy_commands_rp.lua
--- @require pshy_commands_tfm.lua
--- @require pshy_commands_tfm_more.lua
--- @require pshy_entibot.lua
--- @require pshy_emoticons.lua
--- @require pshy_emptyscriptslot.lua
--- @require pshy_fcplatform.lua
--- @require pshy_getxml.lua
--- @require pshy_imagedb_misc.lua
--- @require pshy_loadersync.lua
--- @require pshy_mapdb_more.lua
--- @require pshy_mapinfo.lua
--- @require pshy_motd.lua
--- @require pshy_newgame.lua
--- @require pshy_rain.lua
--- @require pshy_speedfly.lua
--- @require pshy_tfm_enum_fix.lua
--- @require pshy_version.lua
pshy.require("pshy.commands")
pshy.require("pshy.essentials")
--pshy.require("pshy.bases.speedfly")
--pshy.require("pshy.bases.checkpoints")
--pshy.require("pshy.rotations.mapinfo")
--pshy.require("pshy.rotations.newgame")
pshy.require("pshy.utils.rotation")
