--- pshy_essentials.lua
--
-- This module include the most useful submodules i made.
--
-- @author TFM:Pshy#3752 DC:Pshy#7998
--
-- `pshy_assert.lua` increase the informations provided by your asserts.
-- @require pshy_assert.lua
-- `pshy_emptyscriptslot.lua` allow easy adding of a custom script.
-- @require pshy_emptyscriptslot.lua
-- `pshy_print.lua` help formatting prints.
-- @require pshy_print.lua
-- `pshy_tools.lua` is a selection of useful room admin tools.
-- @require pshy_tools.lua
-- `pshy_nofuncorp.lua` allow to run scripts in the tribehouse that would otherwise not.
-- @require pshy_nofuncorp.lua
--
-- @hardmerge

