--- pshy_essentials.lua
--
-- This module include the most useful submodules i made.
--
-- @author TFM:Pshy#3752 DC:Pshy#7998
--
-- @require pshy_assert.lua
-- @require pshy_emptyscriptslot.lua
-- @require pshy_alternatives.lua
--
-- @hardmerge

