--- pshy_bonuses_all.lua
--
-- Require all the bonuses modules.
--
-- @author TFM:Pshy#3752 DC:Pshy#7998
--
-- @require pshy_bonuses_basic.lua
-- @require pshy_bonuses_mario.lua
-- @require pshy_bonuses_misc.lua
-- @require pshy_bonuses_speedfly.lua
--
-- @hardmerge
