--- pshy_tools.lua
--
-- Includes several scripts adding basic features for room admins.
--
-- @author TFM:Pshy#3752 DC:Pshy#7998

-- Scripts from this folder:
-- @require pshy_adminchat.lua
-- @require pshy_ban.lua
-- -- Disabled for performance reasons:
-- --@require pshy_bindkey.lua
-- @require pshy_bindmouse.lua
-- @require pshy_fcplatform.lua
-- @require pshy_lua_commands.lua
-- @require pshy_motd.lua
-- @require pshy_nicks.lua
-- @require pshy_nofuncorp.lua
-- @require pshy_rain.lua
-- @require pshy_tfm_commands.lua

-- Additional scripts from `../fun/`:
-- @require pshy_changeimage.lua
-- @require pshy_fun_commands.lua
-- @require pshy_requests.lua
-- @require pshy_speedfly.lua
--
-- @hardmerge
