--- pshy_tfm_emulator.lua
--
-- Allow to emulate a TFM Lua module outside of TFM.
--
-- @author TFM:Pshy#3752 DC:Pshy#7998
--
-- @require pshy_tfm_emulator_basic_environment.lua
-- @require pshy_tfm_emulator_controls.lua
-- @require pshy_tfm_emulator_game.lua
-- @require pshy_tfm_emulator_players.lua
-- @require pshy_tfm_emulator_room.lua
-- @require pshy_tfm_emulator_time.lua
-- @require pshy_tfm_emulator_ui.lua
--
-- @require_priority DEBUG
