name: "Continuous Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  continuous-build:
    name: "Continuous Build"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v1
    - name: "Update Packages"
      run: sudo apt update
    - name: "Install Lua"
      run: sudo apt install lua5.3
    - name: "Combine"
      run: make re
    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.event_name != 'pull_request'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-build"
        prerelease: true
        title: "Development Build"
        files: |
          tfm_lua/*.tfm.lua.txt

